services:
  vallena.web-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    profiles:
      - production

  vallena.web-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    profiles:
      - development

  vallena.web-build:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    volumes:
      - ./dist:/app/dist
    profiles:
      - build

networks:
  default:
    name: vallena-network
